services:
  elasticsearch01:
    image: elasticsearch:8.11.0
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:8.11.0
    depends_on:
      - elasticsearch01
    ports:
      - 5601:5601